package com.pusilkom.essmobile.model;

import java.io.Serializable;
import java.util.Date;

public class EmployeeAttendance implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.clock_in
     *
     * @mbg.generated
     */
    private Date clockIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.clock_in_location
     *
     * @mbg.generated
     */
    private String clockInLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.clock_out
     *
     * @mbg.generated
     */
    private Date clockOut;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.clock_out_location
     *
     * @mbg.generated
     */
    private String clockOutLocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.activity_detail
     *
     * @mbg.generated
     */
    private String activityDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_attendance.duration
     *
     * @mbg.generated
     */
    private Float duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee_attendance
     *
     * @mbg.generated
     */

    private String dateString;
    private String checkInString;
    private String checkOutString;
    private Integer totalWork;
    private float totalDuration;
    private String workPerWeek;
    private String durationString;
    private String workingMonthString;

    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.id
     *
     * @return the value of employee_attendance.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.id
     *
     * @param id the value for employee_attendance.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.date
     *
     * @return the value of employee_attendance.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.date
     *
     * @param date the value for employee_attendance.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.clock_in
     *
     * @return the value of employee_attendance.clock_in
     *
     * @mbg.generated
     */
    public Date getClockIn() {
        return clockIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.clock_in
     *
     * @param clockIn the value for employee_attendance.clock_in
     *
     * @mbg.generated
     */
    public void setClockIn(Date clockIn) {
        this.clockIn = clockIn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.clock_in_location
     *
     * @return the value of employee_attendance.clock_in_location
     *
     * @mbg.generated
     */
    public String getClockInLocation() {
        return clockInLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.clock_in_location
     *
     * @param clockInLocation the value for employee_attendance.clock_in_location
     *
     * @mbg.generated
     */
    public void setClockInLocation(String clockInLocation) {
        this.clockInLocation = clockInLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.clock_out
     *
     * @return the value of employee_attendance.clock_out
     *
     * @mbg.generated
     */
    public Date getClockOut() {
        return clockOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.clock_out
     *
     * @param clockOut the value for employee_attendance.clock_out
     *
     * @mbg.generated
     */
    public void setClockOut(Date clockOut) {
        this.clockOut = clockOut;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.clock_out_location
     *
     * @return the value of employee_attendance.clock_out_location
     *
     * @mbg.generated
     */
    public String getClockOutLocation() {
        return clockOutLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.clock_out_location
     *
     * @param clockOutLocation the value for employee_attendance.clock_out_location
     *
     * @mbg.generated
     */
    public void setClockOutLocation(String clockOutLocation) {
        this.clockOutLocation = clockOutLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.activity_detail
     *
     * @return the value of employee_attendance.activity_detail
     *
     * @mbg.generated
     */
    public String getActivityDetail() {
        return activityDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.activity_detail
     *
     * @param activityDetail the value for employee_attendance.activity_detail
     *
     * @mbg.generated
     */
    public void setActivityDetail(String activityDetail) {
        this.activityDetail = activityDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.employee_id
     *
     * @return the value of employee_attendance.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.employee_id
     *
     * @param employeeId the value for employee_attendance.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_attendance.duration
     *
     * @return the value of employee_attendance.duration
     *
     * @mbg.generated
     */
    public Float getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_attendance.duration
     *
     * @param duration the value for employee_attendance.duration
     *
     * @mbg.generated
     */
    public void setDuration(Float duration) {
        this.duration = duration;
    }

    public String getDateString() {
        return dateString;
    }

    public void setDateString(String dateString) {
        this.dateString = dateString;
    }

    public String getCheckInString() {
        return checkInString;
    }

    public void setCheckInString(String checkInString) {
        this.checkInString = checkInString;
    }

    public String getCheckOutString() {
        return checkOutString;
    }

    public void setCheckOutString(String checkOutString) {
        this.checkOutString = checkOutString;
    }

    public Integer getTotalWork() {
        return totalWork;
    }

    public void setTotalWork(Integer totalWork) {
        this.totalWork = totalWork;
    }

    public float getTotalDuration() {
        return totalDuration;
    }

    public void setTotalDuration(float totalDuration) {
        this.totalDuration = totalDuration;
    }

    public String getWorkPerWeek() {
        return workPerWeek;
    }

    public void setWorkPerWeek(String workPerWeek) {
        this.workPerWeek = workPerWeek;
    }

    public String getDurationString() {
        return durationString;
    }

    public void setDurationString(String durationString) {
        this.durationString = durationString;
    }

    public String getWorkingMonthString() {
        return workingMonthString;
    }

    public void setWorkingMonthString(String workingMonthString) {
        this.workingMonthString = workingMonthString;
    }

   /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_attendance
     *
     * @mbg.generated
     */


    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EmployeeAttendance other = (EmployeeAttendance) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getClockIn() == null ? other.getClockIn() == null : this.getClockIn().equals(other.getClockIn()))
            && (this.getClockInLocation() == null ? other.getClockInLocation() == null : this.getClockInLocation().equals(other.getClockInLocation()))
            && (this.getClockOut() == null ? other.getClockOut() == null : this.getClockOut().equals(other.getClockOut()))
            && (this.getClockOutLocation() == null ? other.getClockOutLocation() == null : this.getClockOutLocation().equals(other.getClockOutLocation()))
            && (this.getActivityDetail() == null ? other.getActivityDetail() == null : this.getActivityDetail().equals(other.getActivityDetail()))
            && (this.getEmployeeId() == null ? other.getEmployeeId() == null : this.getEmployeeId().equals(other.getEmployeeId()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_attendance
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getClockIn() == null) ? 0 : getClockIn().hashCode());
        result = prime * result + ((getClockInLocation() == null) ? 0 : getClockInLocation().hashCode());
        result = prime * result + ((getClockOut() == null) ? 0 : getClockOut().hashCode());
        result = prime * result + ((getClockOutLocation() == null) ? 0 : getClockOutLocation().hashCode());
        result = prime * result + ((getActivityDetail() == null) ? 0 : getActivityDetail().hashCode());
        result = prime * result + ((getEmployeeId() == null) ? 0 : getEmployeeId().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        return result;
    }

    public EmployeeAttendance(Long id, String checkInString, String checkOutString, String dateString, Integer totalDuration, String activityDetail) {
        this.id = id;
        this.checkInString = checkInString;
        this.checkOutString = !checkOutString.equals("") ? checkOutString : " - ";
        this.dateString = dateString;
        this.totalDuration = totalDuration;
        this.activityDetail = !activityDetail.equals("null") ? activityDetail : " - ";
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();

        sb.append(this.dateString + " | " + "8 Hours, 1 Minutes").append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));

        sb.append("CLOCK-IN : ").append(System.getProperty("line.separator"));
        sb.append(this.checkInString).append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));

        sb.append("CLOCK-OUT : ").append(System.getProperty("line.separator"));
        sb.append(!this.checkOutString.equals("") ? this.checkOutString : "-").append(System.getProperty("line.separator"));
        sb.append(System.getProperty("line.separator"));

        sb.append("ACTIVITY : ").append(System.getProperty("line.separator"));
        sb.append(!this.activityDetail.equals("null") ? this.activityDetail : "-").append(System.getProperty("line.separator"));

        return sb.toString();
    }
}