package com.pusilkom.ess.model;

import java.io.Serializable;
import java.util.Date;

public class EmployeeEducation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.grade
     *
     * @mbg.generated
     */
    private String grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.institution
     *
     * @mbg.generated
     */
    private String institution;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.start_year
     *
     * @mbg.generated
     */
    private String startYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.end_year
     *
     * @mbg.generated
     */
    private String endYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.result
     *
     * @mbg.generated
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee_education.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table employee_education
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.id
     *
     * @return the value of employee_education.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.id
     *
     * @param id the value for employee_education.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.employee_id
     *
     * @return the value of employee_education.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.employee_id
     *
     * @param employeeId the value for employee_education.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.grade
     *
     * @return the value of employee_education.grade
     *
     * @mbg.generated
     */
    public String getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.grade
     *
     * @param grade the value for employee_education.grade
     *
     * @mbg.generated
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.institution
     *
     * @return the value of employee_education.institution
     *
     * @mbg.generated
     */
    public String getInstitution() {
        return institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.institution
     *
     * @param institution the value for employee_education.institution
     *
     * @mbg.generated
     */
    public void setInstitution(String institution) {
        this.institution = institution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.major
     *
     * @return the value of employee_education.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.major
     *
     * @param major the value for employee_education.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.start_year
     *
     * @return the value of employee_education.start_year
     *
     * @mbg.generated
     */
    public String getStartYear() {
        return startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.start_year
     *
     * @param startYear the value for employee_education.start_year
     *
     * @mbg.generated
     */
    public void setStartYear(String startYear) {
        this.startYear = startYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.end_year
     *
     * @return the value of employee_education.end_year
     *
     * @mbg.generated
     */
    public String getEndYear() {
        return endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.end_year
     *
     * @param endYear the value for employee_education.end_year
     *
     * @mbg.generated
     */
    public void setEndYear(String endYear) {
        this.endYear = endYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.result
     *
     * @return the value of employee_education.result
     *
     * @mbg.generated
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.result
     *
     * @param result the value for employee_education.result
     *
     * @mbg.generated
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.created_date
     *
     * @return the value of employee_education.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.created_date
     *
     * @param createdDate the value for employee_education.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.created_by
     *
     * @return the value of employee_education.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.created_by
     *
     * @param createdBy the value for employee_education.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.updated_date
     *
     * @return the value of employee_education.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.updated_date
     *
     * @param updatedDate the value for employee_education.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee_education.updated_by
     *
     * @return the value of employee_education.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee_education.updated_by
     *
     * @param updatedBy the value for employee_education.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_education
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EmployeeEducation other = (EmployeeEducation) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmployeeId() == null ? other.getEmployeeId() == null : this.getEmployeeId().equals(other.getEmployeeId()))
            && (this.getGrade() == null ? other.getGrade() == null : this.getGrade().equals(other.getGrade()))
            && (this.getInstitution() == null ? other.getInstitution() == null : this.getInstitution().equals(other.getInstitution()))
            && (this.getMajor() == null ? other.getMajor() == null : this.getMajor().equals(other.getMajor()))
            && (this.getStartYear() == null ? other.getStartYear() == null : this.getStartYear().equals(other.getStartYear()))
            && (this.getEndYear() == null ? other.getEndYear() == null : this.getEndYear().equals(other.getEndYear()))
            && (this.getResult() == null ? other.getResult() == null : this.getResult().equals(other.getResult()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getUpdatedDate() == null ? other.getUpdatedDate() == null : this.getUpdatedDate().equals(other.getUpdatedDate()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee_education
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmployeeId() == null) ? 0 : getEmployeeId().hashCode());
        result = prime * result + ((getGrade() == null) ? 0 : getGrade().hashCode());
        result = prime * result + ((getInstitution() == null) ? 0 : getInstitution().hashCode());
        result = prime * result + ((getMajor() == null) ? 0 : getMajor().hashCode());
        result = prime * result + ((getStartYear() == null) ? 0 : getStartYear().hashCode());
        result = prime * result + ((getEndYear() == null) ? 0 : getEndYear().hashCode());
        result = prime * result + ((getResult() == null) ? 0 : getResult().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getUpdatedDate() == null) ? 0 : getUpdatedDate().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        return result;
    }
}