package com.pusilkom.ess.model;

import java.io.Serializable;
import java.util.Date;

public class LeaveType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.leave_type_name
     *
     * @mbg.generated
     */
    private String leaveTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.period_type
     *
     * @mbg.generated
     */
    private String periodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.amount
     *
     * @mbg.generated
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.last_updated_by
     *
     * @mbg.generated
     */
    private Integer lastUpdatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.last_updated_date
     *
     * @mbg.generated
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.year
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave_type.leave_type_code
     *
     * @mbg.generated
     */
    private String leaveTypeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave_type
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.id
     *
     * @return the value of leave_type.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.id
     *
     * @param id the value for leave_type.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.leave_type_name
     *
     * @return the value of leave_type.leave_type_name
     *
     * @mbg.generated
     */
    public String getLeaveTypeName() {
        return leaveTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.leave_type_name
     *
     * @param leaveTypeName the value for leave_type.leave_type_name
     *
     * @mbg.generated
     */
    public void setLeaveTypeName(String leaveTypeName) {
        this.leaveTypeName = leaveTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.period_type
     *
     * @return the value of leave_type.period_type
     *
     * @mbg.generated
     */
    public String getPeriodType() {
        return periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.period_type
     *
     * @param periodType the value for leave_type.period_type
     *
     * @mbg.generated
     */
    public void setPeriodType(String periodType) {
        this.periodType = periodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.amount
     *
     * @return the value of leave_type.amount
     *
     * @mbg.generated
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.amount
     *
     * @param amount the value for leave_type.amount
     *
     * @mbg.generated
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.created_by
     *
     * @return the value of leave_type.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.created_by
     *
     * @param createdBy the value for leave_type.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.created_date
     *
     * @return the value of leave_type.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.created_date
     *
     * @param createdDate the value for leave_type.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.last_updated_by
     *
     * @return the value of leave_type.last_updated_by
     *
     * @mbg.generated
     */
    public Integer getLastUpdatedBy() {
        return lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.last_updated_by
     *
     * @param lastUpdatedBy the value for leave_type.last_updated_by
     *
     * @mbg.generated
     */
    public void setLastUpdatedBy(Integer lastUpdatedBy) {
        this.lastUpdatedBy = lastUpdatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.last_updated_date
     *
     * @return the value of leave_type.last_updated_date
     *
     * @mbg.generated
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.last_updated_date
     *
     * @param lastUpdatedDate the value for leave_type.last_updated_date
     *
     * @mbg.generated
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.year
     *
     * @return the value of leave_type.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.year
     *
     * @param year the value for leave_type.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave_type.leave_type_code
     *
     * @return the value of leave_type.leave_type_code
     *
     * @mbg.generated
     */
    public String getLeaveTypeCode() {
        return leaveTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave_type.leave_type_code
     *
     * @param leaveTypeCode the value for leave_type.leave_type_code
     *
     * @mbg.generated
     */
    public void setLeaveTypeCode(String leaveTypeCode) {
        this.leaveTypeCode = leaveTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_type
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LeaveType other = (LeaveType) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLeaveTypeName() == null ? other.getLeaveTypeName() == null : this.getLeaveTypeName().equals(other.getLeaveTypeName()))
            && (this.getPeriodType() == null ? other.getPeriodType() == null : this.getPeriodType().equals(other.getPeriodType()))
            && (this.getAmount() == null ? other.getAmount() == null : this.getAmount().equals(other.getAmount()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getLastUpdatedBy() == null ? other.getLastUpdatedBy() == null : this.getLastUpdatedBy().equals(other.getLastUpdatedBy()))
            && (this.getLastUpdatedDate() == null ? other.getLastUpdatedDate() == null : this.getLastUpdatedDate().equals(other.getLastUpdatedDate()))
            && (this.getYear() == null ? other.getYear() == null : this.getYear().equals(other.getYear()))
            && (this.getLeaveTypeCode() == null ? other.getLeaveTypeCode() == null : this.getLeaveTypeCode().equals(other.getLeaveTypeCode()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave_type
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLeaveTypeName() == null) ? 0 : getLeaveTypeName().hashCode());
        result = prime * result + ((getPeriodType() == null) ? 0 : getPeriodType().hashCode());
        result = prime * result + ((getAmount() == null) ? 0 : getAmount().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getLastUpdatedBy() == null) ? 0 : getLastUpdatedBy().hashCode());
        result = prime * result + ((getLastUpdatedDate() == null) ? 0 : getLastUpdatedDate().hashCode());
        result = prime * result + ((getYear() == null) ? 0 : getYear().hashCode());
        result = prime * result + ((getLeaveTypeCode() == null) ? 0 : getLeaveTypeCode().hashCode());
        return result;
    }
}