package com.pusilkom.ess.model;

import java.io.Serializable;
import java.util.Date;

public class LogActivityDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.date
     *
     * @mbg.generated
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.activity_detail
     *
     * @mbg.generated
     */
    private String activityDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.third_party
     *
     * @mbg.generated
     */
    private String thirdParty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.overtime
     *
     * @mbg.generated
     */
    private Integer overtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.spv_assigned
     *
     * @mbg.generated
     */
    private String spvAssigned;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.project_assign_id
     *
     * @mbg.generated
     */
    private Integer projectAssignId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_activity_detail.sub_pro_id
     *
     * @mbg.generated
     */
    private Integer subProId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table log_activity_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.id
     *
     * @return the value of log_activity_detail.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.id
     *
     * @param id the value for log_activity_detail.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.date
     *
     * @return the value of log_activity_detail.date
     *
     * @mbg.generated
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.date
     *
     * @param date the value for log_activity_detail.date
     *
     * @mbg.generated
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.activity_detail
     *
     * @return the value of log_activity_detail.activity_detail
     *
     * @mbg.generated
     */
    public String getActivityDetail() {
        return activityDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.activity_detail
     *
     * @param activityDetail the value for log_activity_detail.activity_detail
     *
     * @mbg.generated
     */
    public void setActivityDetail(String activityDetail) {
        this.activityDetail = activityDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.third_party
     *
     * @return the value of log_activity_detail.third_party
     *
     * @mbg.generated
     */
    public String getThirdParty() {
        return thirdParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.third_party
     *
     * @param thirdParty the value for log_activity_detail.third_party
     *
     * @mbg.generated
     */
    public void setThirdParty(String thirdParty) {
        this.thirdParty = thirdParty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.duration
     *
     * @return the value of log_activity_detail.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.duration
     *
     * @param duration the value for log_activity_detail.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.overtime
     *
     * @return the value of log_activity_detail.overtime
     *
     * @mbg.generated
     */
    public Integer getOvertime() {
        return overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.overtime
     *
     * @param overtime the value for log_activity_detail.overtime
     *
     * @mbg.generated
     */
    public void setOvertime(Integer overtime) {
        this.overtime = overtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.spv_assigned
     *
     * @return the value of log_activity_detail.spv_assigned
     *
     * @mbg.generated
     */
    public String getSpvAssigned() {
        return spvAssigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.spv_assigned
     *
     * @param spvAssigned the value for log_activity_detail.spv_assigned
     *
     * @mbg.generated
     */
    public void setSpvAssigned(String spvAssigned) {
        this.spvAssigned = spvAssigned;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.project_assign_id
     *
     * @return the value of log_activity_detail.project_assign_id
     *
     * @mbg.generated
     */
    public Integer getProjectAssignId() {
        return projectAssignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.project_assign_id
     *
     * @param projectAssignId the value for log_activity_detail.project_assign_id
     *
     * @mbg.generated
     */
    public void setProjectAssignId(Integer projectAssignId) {
        this.projectAssignId = projectAssignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_activity_detail.sub_pro_id
     *
     * @return the value of log_activity_detail.sub_pro_id
     *
     * @mbg.generated
     */
    public Integer getSubProId() {
        return subProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_activity_detail.sub_pro_id
     *
     * @param subProId the value for log_activity_detail.sub_pro_id
     *
     * @mbg.generated
     */
    public void setSubProId(Integer subProId) {
        this.subProId = subProId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_activity_detail
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LogActivityDetail other = (LogActivityDetail) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getActivityDetail() == null ? other.getActivityDetail() == null : this.getActivityDetail().equals(other.getActivityDetail()))
            && (this.getThirdParty() == null ? other.getThirdParty() == null : this.getThirdParty().equals(other.getThirdParty()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getOvertime() == null ? other.getOvertime() == null : this.getOvertime().equals(other.getOvertime()))
            && (this.getSpvAssigned() == null ? other.getSpvAssigned() == null : this.getSpvAssigned().equals(other.getSpvAssigned()))
            && (this.getProjectAssignId() == null ? other.getProjectAssignId() == null : this.getProjectAssignId().equals(other.getProjectAssignId()))
            && (this.getSubProId() == null ? other.getSubProId() == null : this.getSubProId().equals(other.getSubProId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_activity_detail
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getActivityDetail() == null) ? 0 : getActivityDetail().hashCode());
        result = prime * result + ((getThirdParty() == null) ? 0 : getThirdParty().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getOvertime() == null) ? 0 : getOvertime().hashCode());
        result = prime * result + ((getSpvAssigned() == null) ? 0 : getSpvAssigned().hashCode());
        result = prime * result + ((getProjectAssignId() == null) ? 0 : getProjectAssignId().hashCode());
        result = prime * result + ((getSubProId() == null) ? 0 : getSubProId().hashCode());
        return result;
    }
}