package com.pusilkom.ess.model;

import java.io.Serializable;
import java.util.Date;

public class PettyCash implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.req_number
     *
     * @mbg.generated
     */
    private String reqNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.req_date
     *
     * @mbg.generated
     */
    private Date reqDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.paid_to
     *
     * @mbg.generated
     */
    private Integer paidTo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.req_amount
     *
     * @mbg.generated
     */
    private Integer reqAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.amount_in_word
     *
     * @mbg.generated
     */
    private String amountInWord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.category
     *
     * @mbg.generated
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.funding_source_id
     *
     * @mbg.generated
     */
    private Integer fundingSourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.need_approval
     *
     * @mbg.generated
     */
    private Boolean needApproval;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.reason_of_rejection
     *
     * @mbg.generated
     */
    private String reasonOfRejection;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.approval_date
     *
     * @mbg.generated
     */
    private Date approvalDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.is_approved
     *
     * @mbg.generated
     */
    private Boolean isApproved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.counter
     *
     * @mbg.generated
     */
    private Integer counter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.upload_path
     *
     * @mbg.generated
     */
    private String uploadPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.is_done
     *
     * @mbg.generated
     */
    private Boolean isDone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.approved_by
     *
     * @mbg.generated
     */
    private Integer approvedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.paid_by
     *
     * @mbg.generated
     */
    private Integer paidBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.paid_date
     *
     * @mbg.generated
     */
    private Date paidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.reason_of_cancellation
     *
     * @mbg.generated
     */
    private String reasonOfCancellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.processed_by
     *
     * @mbg.generated
     */
    private Integer processedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column petty_cash.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table petty_cash
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.id
     *
     * @return the value of petty_cash.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.id
     *
     * @param id the value for petty_cash.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.req_number
     *
     * @return the value of petty_cash.req_number
     *
     * @mbg.generated
     */
    public String getReqNumber() {
        return reqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.req_number
     *
     * @param reqNumber the value for petty_cash.req_number
     *
     * @mbg.generated
     */
    public void setReqNumber(String reqNumber) {
        this.reqNumber = reqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.req_date
     *
     * @return the value of petty_cash.req_date
     *
     * @mbg.generated
     */
    public Date getReqDate() {
        return reqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.req_date
     *
     * @param reqDate the value for petty_cash.req_date
     *
     * @mbg.generated
     */
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.paid_to
     *
     * @return the value of petty_cash.paid_to
     *
     * @mbg.generated
     */
    public Integer getPaidTo() {
        return paidTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.paid_to
     *
     * @param paidTo the value for petty_cash.paid_to
     *
     * @mbg.generated
     */
    public void setPaidTo(Integer paidTo) {
        this.paidTo = paidTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.req_amount
     *
     * @return the value of petty_cash.req_amount
     *
     * @mbg.generated
     */
    public Integer getReqAmount() {
        return reqAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.req_amount
     *
     * @param reqAmount the value for petty_cash.req_amount
     *
     * @mbg.generated
     */
    public void setReqAmount(Integer reqAmount) {
        this.reqAmount = reqAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.amount_in_word
     *
     * @return the value of petty_cash.amount_in_word
     *
     * @mbg.generated
     */
    public String getAmountInWord() {
        return amountInWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.amount_in_word
     *
     * @param amountInWord the value for petty_cash.amount_in_word
     *
     * @mbg.generated
     */
    public void setAmountInWord(String amountInWord) {
        this.amountInWord = amountInWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.category
     *
     * @return the value of petty_cash.category
     *
     * @mbg.generated
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.category
     *
     * @param category the value for petty_cash.category
     *
     * @mbg.generated
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.description
     *
     * @return the value of petty_cash.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.description
     *
     * @param description the value for petty_cash.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.funding_source_id
     *
     * @return the value of petty_cash.funding_source_id
     *
     * @mbg.generated
     */
    public Integer getFundingSourceId() {
        return fundingSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.funding_source_id
     *
     * @param fundingSourceId the value for petty_cash.funding_source_id
     *
     * @mbg.generated
     */
    public void setFundingSourceId(Integer fundingSourceId) {
        this.fundingSourceId = fundingSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.need_approval
     *
     * @return the value of petty_cash.need_approval
     *
     * @mbg.generated
     */
    public Boolean getNeedApproval() {
        return needApproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.need_approval
     *
     * @param needApproval the value for petty_cash.need_approval
     *
     * @mbg.generated
     */
    public void setNeedApproval(Boolean needApproval) {
        this.needApproval = needApproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.reason_of_rejection
     *
     * @return the value of petty_cash.reason_of_rejection
     *
     * @mbg.generated
     */
    public String getReasonOfRejection() {
        return reasonOfRejection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.reason_of_rejection
     *
     * @param reasonOfRejection the value for petty_cash.reason_of_rejection
     *
     * @mbg.generated
     */
    public void setReasonOfRejection(String reasonOfRejection) {
        this.reasonOfRejection = reasonOfRejection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.approval_date
     *
     * @return the value of petty_cash.approval_date
     *
     * @mbg.generated
     */
    public Date getApprovalDate() {
        return approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.approval_date
     *
     * @param approvalDate the value for petty_cash.approval_date
     *
     * @mbg.generated
     */
    public void setApprovalDate(Date approvalDate) {
        this.approvalDate = approvalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.is_approved
     *
     * @return the value of petty_cash.is_approved
     *
     * @mbg.generated
     */
    public Boolean getIsApproved() {
        return isApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.is_approved
     *
     * @param isApproved the value for petty_cash.is_approved
     *
     * @mbg.generated
     */
    public void setIsApproved(Boolean isApproved) {
        this.isApproved = isApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.counter
     *
     * @return the value of petty_cash.counter
     *
     * @mbg.generated
     */
    public Integer getCounter() {
        return counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.counter
     *
     * @param counter the value for petty_cash.counter
     *
     * @mbg.generated
     */
    public void setCounter(Integer counter) {
        this.counter = counter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.upload_path
     *
     * @return the value of petty_cash.upload_path
     *
     * @mbg.generated
     */
    public String getUploadPath() {
        return uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.upload_path
     *
     * @param uploadPath the value for petty_cash.upload_path
     *
     * @mbg.generated
     */
    public void setUploadPath(String uploadPath) {
        this.uploadPath = uploadPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.created_by
     *
     * @return the value of petty_cash.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.created_by
     *
     * @param createdBy the value for petty_cash.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.is_done
     *
     * @return the value of petty_cash.is_done
     *
     * @mbg.generated
     */
    public Boolean getIsDone() {
        return isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.is_done
     *
     * @param isDone the value for petty_cash.is_done
     *
     * @mbg.generated
     */
    public void setIsDone(Boolean isDone) {
        this.isDone = isDone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.approved_by
     *
     * @return the value of petty_cash.approved_by
     *
     * @mbg.generated
     */
    public Integer getApprovedBy() {
        return approvedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.approved_by
     *
     * @param approvedBy the value for petty_cash.approved_by
     *
     * @mbg.generated
     */
    public void setApprovedBy(Integer approvedBy) {
        this.approvedBy = approvedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.paid_by
     *
     * @return the value of petty_cash.paid_by
     *
     * @mbg.generated
     */
    public Integer getPaidBy() {
        return paidBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.paid_by
     *
     * @param paidBy the value for petty_cash.paid_by
     *
     * @mbg.generated
     */
    public void setPaidBy(Integer paidBy) {
        this.paidBy = paidBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.paid_date
     *
     * @return the value of petty_cash.paid_date
     *
     * @mbg.generated
     */
    public Date getPaidDate() {
        return paidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.paid_date
     *
     * @param paidDate the value for petty_cash.paid_date
     *
     * @mbg.generated
     */
    public void setPaidDate(Date paidDate) {
        this.paidDate = paidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.reason_of_cancellation
     *
     * @return the value of petty_cash.reason_of_cancellation
     *
     * @mbg.generated
     */
    public String getReasonOfCancellation() {
        return reasonOfCancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.reason_of_cancellation
     *
     * @param reasonOfCancellation the value for petty_cash.reason_of_cancellation
     *
     * @mbg.generated
     */
    public void setReasonOfCancellation(String reasonOfCancellation) {
        this.reasonOfCancellation = reasonOfCancellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.processed_by
     *
     * @return the value of petty_cash.processed_by
     *
     * @mbg.generated
     */
    public Integer getProcessedBy() {
        return processedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.processed_by
     *
     * @param processedBy the value for petty_cash.processed_by
     *
     * @mbg.generated
     */
    public void setProcessedBy(Integer processedBy) {
        this.processedBy = processedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column petty_cash.created_date
     *
     * @return the value of petty_cash.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column petty_cash.created_date
     *
     * @param createdDate the value for petty_cash.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petty_cash
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PettyCash other = (PettyCash) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getReqNumber() == null ? other.getReqNumber() == null : this.getReqNumber().equals(other.getReqNumber()))
            && (this.getReqDate() == null ? other.getReqDate() == null : this.getReqDate().equals(other.getReqDate()))
            && (this.getPaidTo() == null ? other.getPaidTo() == null : this.getPaidTo().equals(other.getPaidTo()))
            && (this.getReqAmount() == null ? other.getReqAmount() == null : this.getReqAmount().equals(other.getReqAmount()))
            && (this.getAmountInWord() == null ? other.getAmountInWord() == null : this.getAmountInWord().equals(other.getAmountInWord()))
            && (this.getCategory() == null ? other.getCategory() == null : this.getCategory().equals(other.getCategory()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getFundingSourceId() == null ? other.getFundingSourceId() == null : this.getFundingSourceId().equals(other.getFundingSourceId()))
            && (this.getNeedApproval() == null ? other.getNeedApproval() == null : this.getNeedApproval().equals(other.getNeedApproval()))
            && (this.getReasonOfRejection() == null ? other.getReasonOfRejection() == null : this.getReasonOfRejection().equals(other.getReasonOfRejection()))
            && (this.getApprovalDate() == null ? other.getApprovalDate() == null : this.getApprovalDate().equals(other.getApprovalDate()))
            && (this.getIsApproved() == null ? other.getIsApproved() == null : this.getIsApproved().equals(other.getIsApproved()))
            && (this.getCounter() == null ? other.getCounter() == null : this.getCounter().equals(other.getCounter()))
            && (this.getUploadPath() == null ? other.getUploadPath() == null : this.getUploadPath().equals(other.getUploadPath()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getIsDone() == null ? other.getIsDone() == null : this.getIsDone().equals(other.getIsDone()))
            && (this.getApprovedBy() == null ? other.getApprovedBy() == null : this.getApprovedBy().equals(other.getApprovedBy()))
            && (this.getPaidBy() == null ? other.getPaidBy() == null : this.getPaidBy().equals(other.getPaidBy()))
            && (this.getPaidDate() == null ? other.getPaidDate() == null : this.getPaidDate().equals(other.getPaidDate()))
            && (this.getReasonOfCancellation() == null ? other.getReasonOfCancellation() == null : this.getReasonOfCancellation().equals(other.getReasonOfCancellation()))
            && (this.getProcessedBy() == null ? other.getProcessedBy() == null : this.getProcessedBy().equals(other.getProcessedBy()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table petty_cash
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getReqNumber() == null) ? 0 : getReqNumber().hashCode());
        result = prime * result + ((getReqDate() == null) ? 0 : getReqDate().hashCode());
        result = prime * result + ((getPaidTo() == null) ? 0 : getPaidTo().hashCode());
        result = prime * result + ((getReqAmount() == null) ? 0 : getReqAmount().hashCode());
        result = prime * result + ((getAmountInWord() == null) ? 0 : getAmountInWord().hashCode());
        result = prime * result + ((getCategory() == null) ? 0 : getCategory().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getFundingSourceId() == null) ? 0 : getFundingSourceId().hashCode());
        result = prime * result + ((getNeedApproval() == null) ? 0 : getNeedApproval().hashCode());
        result = prime * result + ((getReasonOfRejection() == null) ? 0 : getReasonOfRejection().hashCode());
        result = prime * result + ((getApprovalDate() == null) ? 0 : getApprovalDate().hashCode());
        result = prime * result + ((getIsApproved() == null) ? 0 : getIsApproved().hashCode());
        result = prime * result + ((getCounter() == null) ? 0 : getCounter().hashCode());
        result = prime * result + ((getUploadPath() == null) ? 0 : getUploadPath().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getIsDone() == null) ? 0 : getIsDone().hashCode());
        result = prime * result + ((getApprovedBy() == null) ? 0 : getApprovedBy().hashCode());
        result = prime * result + ((getPaidBy() == null) ? 0 : getPaidBy().hashCode());
        result = prime * result + ((getPaidDate() == null) ? 0 : getPaidDate().hashCode());
        result = prime * result + ((getReasonOfCancellation() == null) ? 0 : getReasonOfCancellation().hashCode());
        result = prime * result + ((getProcessedBy() == null) ? 0 : getProcessedBy().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        return result;
    }
}