package com.pusilkom.ess.model;

import java.io.Serializable;
import java.util.Date;

public class ProjectContract implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.project_id
     *
     * @mbg.generated
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.contract_number
     *
     * @mbg.generated
     */
    private String contractNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.contract_date
     *
     * @mbg.generated
     */
    private Date contractDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.signee1
     *
     * @mbg.generated
     */
    private String signee1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.signee2
     *
     * @mbg.generated
     */
    private String signee2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.created_date
     *
     * @mbg.generated
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.created_by
     *
     * @mbg.generated
     */
    private Integer createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.updated_date
     *
     * @mbg.generated
     */
    private Date updatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_contract.updated_by
     *
     * @mbg.generated
     */
    private Integer updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_contract
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.id
     *
     * @return the value of project_contract.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.id
     *
     * @param id the value for project_contract.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.project_id
     *
     * @return the value of project_contract.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.project_id
     *
     * @param projectId the value for project_contract.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.contract_number
     *
     * @return the value of project_contract.contract_number
     *
     * @mbg.generated
     */
    public String getContractNumber() {
        return contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.contract_number
     *
     * @param contractNumber the value for project_contract.contract_number
     *
     * @mbg.generated
     */
    public void setContractNumber(String contractNumber) {
        this.contractNumber = contractNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.contract_date
     *
     * @return the value of project_contract.contract_date
     *
     * @mbg.generated
     */
    public Date getContractDate() {
        return contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.contract_date
     *
     * @param contractDate the value for project_contract.contract_date
     *
     * @mbg.generated
     */
    public void setContractDate(Date contractDate) {
        this.contractDate = contractDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.signee1
     *
     * @return the value of project_contract.signee1
     *
     * @mbg.generated
     */
    public String getSignee1() {
        return signee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.signee1
     *
     * @param signee1 the value for project_contract.signee1
     *
     * @mbg.generated
     */
    public void setSignee1(String signee1) {
        this.signee1 = signee1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.signee2
     *
     * @return the value of project_contract.signee2
     *
     * @mbg.generated
     */
    public String getSignee2() {
        return signee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.signee2
     *
     * @param signee2 the value for project_contract.signee2
     *
     * @mbg.generated
     */
    public void setSignee2(String signee2) {
        this.signee2 = signee2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.created_date
     *
     * @return the value of project_contract.created_date
     *
     * @mbg.generated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.created_date
     *
     * @param createdDate the value for project_contract.created_date
     *
     * @mbg.generated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.created_by
     *
     * @return the value of project_contract.created_by
     *
     * @mbg.generated
     */
    public Integer getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.created_by
     *
     * @param createdBy the value for project_contract.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.updated_date
     *
     * @return the value of project_contract.updated_date
     *
     * @mbg.generated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.updated_date
     *
     * @param updatedDate the value for project_contract.updated_date
     *
     * @mbg.generated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_contract.updated_by
     *
     * @return the value of project_contract.updated_by
     *
     * @mbg.generated
     */
    public Integer getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_contract.updated_by
     *
     * @param updatedBy the value for project_contract.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Integer updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_contract
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ProjectContract other = (ProjectContract) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getContractNumber() == null ? other.getContractNumber() == null : this.getContractNumber().equals(other.getContractNumber()))
            && (this.getContractDate() == null ? other.getContractDate() == null : this.getContractDate().equals(other.getContractDate()))
            && (this.getSignee1() == null ? other.getSignee1() == null : this.getSignee1().equals(other.getSignee1()))
            && (this.getSignee2() == null ? other.getSignee2() == null : this.getSignee2().equals(other.getSignee2()))
            && (this.getCreatedDate() == null ? other.getCreatedDate() == null : this.getCreatedDate().equals(other.getCreatedDate()))
            && (this.getCreatedBy() == null ? other.getCreatedBy() == null : this.getCreatedBy().equals(other.getCreatedBy()))
            && (this.getUpdatedDate() == null ? other.getUpdatedDate() == null : this.getUpdatedDate().equals(other.getUpdatedDate()))
            && (this.getUpdatedBy() == null ? other.getUpdatedBy() == null : this.getUpdatedBy().equals(other.getUpdatedBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_contract
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getContractNumber() == null) ? 0 : getContractNumber().hashCode());
        result = prime * result + ((getContractDate() == null) ? 0 : getContractDate().hashCode());
        result = prime * result + ((getSignee1() == null) ? 0 : getSignee1().hashCode());
        result = prime * result + ((getSignee2() == null) ? 0 : getSignee2().hashCode());
        result = prime * result + ((getCreatedDate() == null) ? 0 : getCreatedDate().hashCode());
        result = prime * result + ((getCreatedBy() == null) ? 0 : getCreatedBy().hashCode());
        result = prime * result + ((getUpdatedDate() == null) ? 0 : getUpdatedDate().hashCode());
        result = prime * result + ((getUpdatedBy() == null) ? 0 : getUpdatedBy().hashCode());
        return result;
    }
}