package com.pusilkom.ess.model;

import java.io.Serializable;
import java.util.Date;

public class RecapLogActivityReport implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recap_log_activity_report.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recap_log_activity_report.employee_id
     *
     * @mbg.generated
     */
    private Integer employeeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recap_log_activity_report.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recap_log_activity_report.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recap_log_activity_report.path
     *
     * @mbg.generated
     */
    private String path;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recap_log_activity_report.sub_project_id
     *
     * @mbg.generated
     */
    private Integer subProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table recap_log_activity_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recap_log_activity_report.id
     *
     * @return the value of recap_log_activity_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recap_log_activity_report.id
     *
     * @param id the value for recap_log_activity_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recap_log_activity_report.employee_id
     *
     * @return the value of recap_log_activity_report.employee_id
     *
     * @mbg.generated
     */
    public Integer getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recap_log_activity_report.employee_id
     *
     * @param employeeId the value for recap_log_activity_report.employee_id
     *
     * @mbg.generated
     */
    public void setEmployeeId(Integer employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recap_log_activity_report.start_date
     *
     * @return the value of recap_log_activity_report.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recap_log_activity_report.start_date
     *
     * @param startDate the value for recap_log_activity_report.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recap_log_activity_report.end_date
     *
     * @return the value of recap_log_activity_report.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recap_log_activity_report.end_date
     *
     * @param endDate the value for recap_log_activity_report.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recap_log_activity_report.path
     *
     * @return the value of recap_log_activity_report.path
     *
     * @mbg.generated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recap_log_activity_report.path
     *
     * @param path the value for recap_log_activity_report.path
     *
     * @mbg.generated
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recap_log_activity_report.sub_project_id
     *
     * @return the value of recap_log_activity_report.sub_project_id
     *
     * @mbg.generated
     */
    public Integer getSubProjectId() {
        return subProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recap_log_activity_report.sub_project_id
     *
     * @param subProjectId the value for recap_log_activity_report.sub_project_id
     *
     * @mbg.generated
     */
    public void setSubProjectId(Integer subProjectId) {
        this.subProjectId = subProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recap_log_activity_report
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RecapLogActivityReport other = (RecapLogActivityReport) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmployeeId() == null ? other.getEmployeeId() == null : this.getEmployeeId().equals(other.getEmployeeId()))
            && (this.getStartDate() == null ? other.getStartDate() == null : this.getStartDate().equals(other.getStartDate()))
            && (this.getEndDate() == null ? other.getEndDate() == null : this.getEndDate().equals(other.getEndDate()))
            && (this.getPath() == null ? other.getPath() == null : this.getPath().equals(other.getPath()))
            && (this.getSubProjectId() == null ? other.getSubProjectId() == null : this.getSubProjectId().equals(other.getSubProjectId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recap_log_activity_report
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmployeeId() == null) ? 0 : getEmployeeId().hashCode());
        result = prime * result + ((getStartDate() == null) ? 0 : getStartDate().hashCode());
        result = prime * result + ((getEndDate() == null) ? 0 : getEndDate().hashCode());
        result = prime * result + ((getPath() == null) ? 0 : getPath().hashCode());
        result = prime * result + ((getSubProjectId() == null) ? 0 : getSubProjectId().hashCode());
        return result;
    }
}