package com.pusilkom.ess.model;

import java.io.Serializable;

public class RoleHasPermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role_has_permission.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role_has_permission.id_role
     *
     * @mbg.generated
     */
    private Long idRole;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.role_has_permission.id_permission
     *
     * @mbg.generated
     */
    private Long idPermission;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.role_has_permission
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.role_has_permission.id
     *
     * @return the value of public.role_has_permission.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.role_has_permission.id
     *
     * @param id the value for public.role_has_permission.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.role_has_permission.id_role
     *
     * @return the value of public.role_has_permission.id_role
     *
     * @mbg.generated
     */
    public Long getIdRole() {
        return idRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.role_has_permission.id_role
     *
     * @param idRole the value for public.role_has_permission.id_role
     *
     * @mbg.generated
     */
    public void setIdRole(Long idRole) {
        this.idRole = idRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column public.role_has_permission.id_permission
     *
     * @return the value of public.role_has_permission.id_permission
     *
     * @mbg.generated
     */
    public Long getIdPermission() {
        return idPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column public.role_has_permission.id_permission
     *
     * @param idPermission the value for public.role_has_permission.id_permission
     *
     * @mbg.generated
     */
    public void setIdPermission(Long idPermission) {
        this.idPermission = idPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_has_permission
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoleHasPermission other = (RoleHasPermission) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getIdRole() == null ? other.getIdRole() == null : this.getIdRole().equals(other.getIdRole()))
            && (this.getIdPermission() == null ? other.getIdPermission() == null : this.getIdPermission().equals(other.getIdPermission()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.role_has_permission
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getIdRole() == null) ? 0 : getIdRole().hashCode());
        result = prime * result + ((getIdPermission() == null) ? 0 : getIdPermission().hashCode());
        return result;
    }
}